name: mvnrepository
on:
  push:
    branches: [ servers ]
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:
jobs:
  get_servers_from_instances_list:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Clone local repository locally
      uses: actions/checkout@v3
    - name: Install requirements
      run: |
        sudo apt install curl -y
        sudo apt install jq -y
    - name: Run extraction sequence
    # instances.social app id is 628232131
      run: |
        curl "https://instances.social/api/1.0/instances/list?count=0&include_dead=false&sort_by=users&sort_order=desc" -H "Authorization: Bearer ${{secrets.INSTANCES_SOCIAL_TOKEN}}" | jq .instances.[].name > servers.json
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: servers
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: Updated server list
        COMMIT-NAME: 🤖 GitHub Action
        COMMIT_EMAIL: update_servers.yaml@github.actions